"""
MMSI Maritime Identification Digits (MID) → ISO 3166-1 alpha-2 country codes.

First 3 digits of a ship MMSI identify the flag state (ITU Radio Regulations
Appendix 43). Used to pick a vessel flag for the detail screen.
"""

from __future__ import annotations

# MID → (ISO alpha-2, country name). Common maritime registries; not exhaustive.
_MID_TABLE: dict[int, tuple[str, str]] = {
    201: ("al", "Albania"),
    202: ("ad", "Andorra"),
    203: ("at", "Austria"),
    204: ("pt", "Portugal"),  # Azores
    205: ("be", "Belgium"),
    206: ("by", "Belarus"),
    207: ("bg", "Bulgaria"),
    208: ("va", "Vatican"),
    209: ("cy", "Cyprus"),
    210: ("cy", "Cyprus"),
    211: ("de", "Germany"),
    212: ("cy", "Cyprus"),
    213: ("ge", "Georgia"),
    214: ("md", "Moldova"),
    215: ("mt", "Malta"),
    216: ("am", "Armenia"),
    218: ("de", "Germany"),
    219: ("dk", "Denmark"),
    220: ("dk", "Denmark"),
    224: ("es", "Spain"),
    225: ("es", "Spain"),
    226: ("fr", "France"),
    227: ("fr", "France"),
    228: ("fr", "France"),
    229: ("mt", "Malta"),
    230: ("fi", "Finland"),
    231: ("fo", "Faroe Islands"),
    232: ("gb", "United Kingdom"),
    233: ("gb", "United Kingdom"),
    234: ("gb", "United Kingdom"),
    235: ("gb", "United Kingdom"),
    236: ("gi", "Gibraltar"),
    237: ("gr", "Greece"),
    238: ("hr", "Croatia"),
    239: ("gr", "Greece"),
    240: ("gr", "Greece"),
    241: ("gr", "Greece"),
    242: ("ma", "Morocco"),
    243: ("hu", "Hungary"),
    244: ("nl", "Netherlands"),
    245: ("nl", "Netherlands"),
    246: ("nl", "Netherlands"),
    247: ("it", "Italy"),
    248: ("mt", "Malta"),
    249: ("mt", "Malta"),
    250: ("ie", "Ireland"),
    251: ("is", "Iceland"),
    252: ("li", "Liechtenstein"),
    253: ("lu", "Luxembourg"),
    254: ("mc", "Monaco"),
    255: ("pt", "Portugal"),  # Madeira
    256: ("mt", "Malta"),
    257: ("no", "Norway"),
    258: ("no", "Norway"),
    259: ("no", "Norway"),
    261: ("pl", "Poland"),
    262: ("me", "Montenegro"),
    263: ("pt", "Portugal"),
    264: ("ro", "Romania"),
    265: ("se", "Sweden"),
    266: ("se", "Sweden"),
    267: ("sk", "Slovakia"),
    268: ("sm", "San Marino"),
    269: ("ch", "Switzerland"),
    270: ("cz", "Czechia"),
    271: ("tr", "Turkey"),
    272: ("ua", "Ukraine"),
    273: ("ru", "Russia"),
    274: ("mk", "North Macedonia"),
    275: ("lv", "Latvia"),
    276: ("ee", "Estonia"),
    277: ("lt", "Lithuania"),
    278: ("si", "Slovenia"),
    279: ("rs", "Serbia"),
    301: ("ai", "Anguilla"),
    303: ("us", "United States"),  # Alaska
    304: ("ag", "Antigua and Barbuda"),
    305: ("ag", "Antigua and Barbuda"),
    306: ("cw", "Curaçao"),
    307: ("aw", "Aruba"),
    308: ("bs", "Bahamas"),
    309: ("bs", "Bahamas"),
    310: ("bm", "Bermuda"),
    311: ("bs", "Bahamas"),
    312: ("bz", "Belize"),
    314: ("bb", "Barbados"),
    316: ("ca", "Canada"),
    319: ("ky", "Cayman Islands"),
    321: ("cr", "Costa Rica"),
    323: ("cu", "Cuba"),
    325: ("dm", "Dominica"),
    327: ("do", "Dominican Republic"),
    329: ("gp", "Guadeloupe"),
    330: ("gd", "Grenada"),
    331: ("gl", "Greenland"),
    332: ("gt", "Guatemala"),
    334: ("hn", "Honduras"),
    336: ("ht", "Haiti"),
    338: ("us", "United States"),
    339: ("jm", "Jamaica"),
    341: ("kn", "Saint Kitts and Nevis"),
    343: ("lc", "Saint Lucia"),
    345: ("mx", "Mexico"),
    347: ("mq", "Martinique"),
    348: ("ms", "Montserrat"),
    350: ("ni", "Nicaragua"),
    351: ("pa", "Panama"),
    352: ("pa", "Panama"),
    353: ("pa", "Panama"),
    354: ("pa", "Panama"),
    355: ("pa", "Panama"),
    356: ("pa", "Panama"),
    357: ("pa", "Panama"),
    358: ("pr", "Puerto Rico"),
    359: ("sv", "El Salvador"),
    361: ("pm", "Saint Pierre and Miquelon"),
    362: ("tt", "Trinidad and Tobago"),
    364: ("tc", "Turks and Caicos"),
    366: ("us", "United States"),
    367: ("us", "United States"),
    368: ("us", "United States"),
    369: ("us", "United States"),
    370: ("pa", "Panama"),
    371: ("pa", "Panama"),
    372: ("pa", "Panama"),
    373: ("pa", "Panama"),
    374: ("pa", "Panama"),
    375: ("vc", "Saint Vincent"),
    376: ("vc", "Saint Vincent"),
    377: ("vc", "Saint Vincent"),
    378: ("vg", "British Virgin Islands"),
    379: ("vi", "US Virgin Islands"),
    401: ("af", "Afghanistan"),
    403: ("sa", "Saudi Arabia"),
    405: ("bd", "Bangladesh"),
    408: ("bh", "Bahrain"),
    410: ("bt", "Bhutan"),
    412: ("cn", "China"),
    413: ("cn", "China"),
    414: ("cn", "China"),
    416: ("tw", "Taiwan"),
    417: ("lk", "Sri Lanka"),
    419: ("in", "India"),
    422: ("ir", "Iran"),
    423: ("az", "Azerbaijan"),
    425: ("iq", "Iraq"),
    428: ("il", "Israel"),
    431: ("jp", "Japan"),
    432: ("jp", "Japan"),
    434: ("tm", "Turkmenistan"),
    436: ("kz", "Kazakhstan"),
    437: ("uz", "Uzbekistan"),
    438: ("jo", "Jordan"),
    440: ("kr", "South Korea"),
    441: ("kr", "South Korea"),
    443: ("ps", "Palestine"),
    445: ("kp", "North Korea"),
    447: ("kw", "Kuwait"),
    450: ("lb", "Lebanon"),
    451: ("kg", "Kyrgyzstan"),
    453: ("mo", "Macao"),
    455: ("mv", "Maldives"),
    457: ("mn", "Mongolia"),
    459: ("np", "Nepal"),
    461: ("om", "Oman"),
    463: ("pk", "Pakistan"),
    466: ("qa", "Qatar"),
    468: ("sy", "Syria"),
    470: ("ae", "United Arab Emirates"),
    471: ("ae", "United Arab Emirates"),
    472: ("tj", "Tajikistan"),
    473: ("ye", "Yemen"),
    475: ("ye", "Yemen"),
    477: ("hk", "Hong Kong"),
    478: ("ba", "Bosnia and Herzegovina"),
    501: ("aq", "Adelie Land"),
    503: ("au", "Australia"),
    506: ("mm", "Myanmar"),
    508: ("bn", "Brunei"),
    510: ("fm", "Micronesia"),
    511: ("pw", "Palau"),
    512: ("nz", "New Zealand"),
    514: ("kh", "Cambodia"),
    515: ("kh", "Cambodia"),
    516: ("cx", "Christmas Island"),
    518: ("ck", "Cook Islands"),
    520: ("fj", "Fiji"),
    523: ("cc", "Cocos Islands"),
    525: ("id", "Indonesia"),
    529: ("ki", "Kiribati"),
    531: ("la", "Laos"),
    533: ("my", "Malaysia"),
    536: ("mp", "Northern Mariana Islands"),
    538: ("mh", "Marshall Islands"),
    540: ("nc", "New Caledonia"),
    542: ("nu", "Niue"),
    544: ("nr", "Nauru"),
    546: ("pf", "French Polynesia"),
    548: ("ph", "Philippines"),
    553: ("pg", "Papua New Guinea"),
    555: ("pn", "Pitcairn"),
    557: ("sb", "Solomon Islands"),
    559: ("as", "American Samoa"),
    561: ("ws", "Samoa"),
    563: ("sg", "Singapore"),
    564: ("sg", "Singapore"),
    565: ("sg", "Singapore"),
    566: ("sg", "Singapore"),
    567: ("th", "Thailand"),
    570: ("to", "Tonga"),
    572: ("tv", "Tuvalu"),
    574: ("vn", "Vietnam"),
    576: ("vu", "Vanuatu"),
    577: ("vu", "Vanuatu"),
    578: ("wf", "Wallis and Futuna"),
    601: ("za", "South Africa"),
    603: ("ao", "Angola"),
    605: ("dz", "Algeria"),
    607: ("tf", "French Southern Territories"),
    608: ("io", "British Indian Ocean Territory"),  # Ascension often mapped elsewhere
    609: ("bi", "Burundi"),
    610: ("bj", "Benin"),
    611: ("bw", "Botswana"),
    612: ("cf", "Central African Republic"),
    613: ("cm", "Cameroon"),
    615: ("cg", "Congo"),
    616: ("km", "Comoros"),
    617: ("cv", "Cape Verde"),
    618: ("fr", "France"),  # Crozet
    619: ("ci", "Ivory Coast"),
    620: ("km", "Comoros"),
    621: ("dj", "Djibouti"),
    622: ("eg", "Egypt"),
    624: ("et", "Ethiopia"),
    625: ("er", "Eritrea"),
    626: ("ga", "Gabon"),
    627: ("gh", "Ghana"),
    629: ("gm", "Gambia"),
    630: ("gw", "Guinea-Bissau"),
    631: ("gq", "Equatorial Guinea"),
    632: ("gn", "Guinea"),
    633: ("bf", "Burkina Faso"),
    634: ("ke", "Kenya"),
    635: ("fr", "France"),  # Kerguelen
    636: ("lr", "Liberia"),
    637: ("lr", "Liberia"),
    638: ("ss", "South Sudan"),
    642: ("ly", "Libya"),
    644: ("ls", "Lesotho"),
    645: ("mu", "Mauritius"),
    647: ("mg", "Madagascar"),
    649: ("ml", "Mali"),
    650: ("mz", "Mozambique"),
    654: ("mr", "Mauritania"),
    655: ("mw", "Malawi"),
    656: ("ne", "Niger"),
    657: ("ng", "Nigeria"),
    659: ("na", "Namibia"),
    660: ("re", "Réunion"),
    661: ("rw", "Rwanda"),
    662: ("sd", "Sudan"),
    663: ("sn", "Senegal"),
    664: ("sc", "Seychelles"),
    665: ("sh", "Saint Helena"),
    666: ("so", "Somalia"),
    667: ("sl", "Sierra Leone"),
    668: ("st", "Sao Tome and Principe"),
    669: ("sz", "Eswatini"),
    670: ("td", "Chad"),
    671: ("tg", "Togo"),
    672: ("tn", "Tunisia"),
    674: ("tz", "Tanzania"),
    675: ("ug", "Uganda"),
    676: ("cd", "DR Congo"),
    677: ("tz", "Tanzania"),
    678: ("zm", "Zambia"),
    679: ("zw", "Zimbabwe"),
    701: ("ar", "Argentina"),
    710: ("br", "Brazil"),
    720: ("bo", "Bolivia"),
    725: ("cl", "Chile"),
    730: ("co", "Colombia"),
    735: ("ec", "Ecuador"),
    740: ("fk", "Falkland Islands"),
    745: ("gf", "French Guiana"),
    750: ("gy", "Guyana"),
    755: ("py", "Paraguay"),
    760: ("pe", "Peru"),
    765: ("sr", "Suriname"),
    770: ("uy", "Uruguay"),
    775: ("ve", "Venezuela"),
}


def mid_from_mmsi(mmsi) -> int | None:
    """Extract MID digits from an MMSI (ship / common formats)."""
    try:
        n = int(mmsi)
    except (TypeError, ValueError):
        digits = "".join(ch for ch in str(mmsi or "") if ch.isdigit())
        if len(digits) < 3:
            return None
        n = int(digits)
    s = f"{n:09d}"[-9:]
    if s.startswith(("97", "98", "99")):
        # Aids / craft / SAR — MID is digits 3–5
        return int(s[2:5])
    if s.startswith("00"):
        return int(s[2:5])  # coast station
    if s[0] in "234567":
        return int(s[0:3])
    return None


def country_for_mmsi(mmsi) -> tuple[str, str] | None:
    """Return (iso2 lowercase, country name) or None."""
    mid = mid_from_mmsi(mmsi)
    if mid is None:
        return None
    return _MID_TABLE.get(mid)


def flag_iso2_for_mmsi(mmsi) -> str:
    """ISO alpha-2 for flag asset lookup, or empty string."""
    info = country_for_mmsi(mmsi)
    return info[0] if info else ""


def country_name_for_mmsi(mmsi) -> str:
    info = country_for_mmsi(mmsi)
    return info[1] if info else ""
